global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "certificates-api"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ["host.docker.internal:7277"]

  - job_name: "certificates-registryconnector"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets: ["host.docker.internal:7061"]

  - job_name: "Prometheus"
    static_configs:
    - targets: [localhost:9090]
